# Generated by Django 4.2 on 2026-05-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_school_name_userprofile_schoolname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='schoolname',
        ),
    ]
