# Generated by Django 4.2 on 2026-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='expense_bills/'),
        ),
    ]
