# Generated by Django 4.2 on 2026-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_bill_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transport_bus_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transport_driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transport_route',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
