# Generated by Django 4.2 on 2026-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_common_subjects'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['week_start_date', 'day', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='week_start_date',
            field=models.DateField(blank=True, help_text='Start date of the calendar week', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'week_start_date', 'day', 'start_time')},
        ),
    ]
