# Generated by Django 4.2 on 2026-06-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_login_password_teacher_login_username'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to='teachers.teacher'),
        ),
    ]
