# Generated by Django 4.2 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['class_name']},
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('term1', 'Term 1'), ('term2', 'Term 2'), ('books', 'Books'), ('library', 'Library')], default='tuition', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feecollection',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('upi', 'UPI')], max_length=20),
        ),
    ]
