# Generated by Django 4.2 on 2026-05-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
