# Generated by Django 4.2 on 2026-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feecollection_account_number_feecollection_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
