# Generated by Django 4.2 on 2026-05-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_blood_group'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='class_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_classes', to='teachers.teacher'),
        ),
    ]
