# Generated by Django 4.2 on 2026-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='login_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
