# Generated by Django 4.2 on 2026-05-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_common_subjects'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='classes.section'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('slip_test', 'Slip Test'), ('week_test', 'Week Test'), ('unit_test', 'Unit Test'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('fa1', 'FA1'), ('fa2', 'FA2'), ('pre_final', 'Pre Final'), ('final', 'Final'), ('mid_term', 'Mid Term'), ('practical', 'Practical')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('exam', 'section', 'subject')},
        ),
    ]
